texts = {
    'en': {
        'start_message': '<b> Terms and conditions of using the dating bot to create 🌟 </b> \n\n 1. <b>Bot purpose 💍 </b> \n \tThis bot was created for people who are looking for a serious relationship and strive to create a strong family . We welcome sincerity , respect and readiness for long-term commitments . \n\n 2. <b> Age restriction 🚫 </b> \n \tThe bot is only allowed to be used by persons over 18 years of age. By registering in the bot , you confirm that you have reached the age of majority . \n\n 3. <b>Registration and questionnaire 📝 </b> \n \tTo start using the bot, you need to fill out a questionnaire , indicating reliable information about yourself . The more honestly and in detail you tell about yourself , the higher the chance of finding the right person . \n\n 4. <b> Respect for other users </b> \n \tWe do not tolerate insults , rudeness or disrespectful behavior . Every user deserves to be treated with care and kindness . \n\n 5. <b> Sincerity in communication 💬 </b> \n \tWe encourage you to be honest in your intentions . If you are looking for a serious relationship , indicate this in your profile and communication . \n\n 6. <b> Visibility of profiles 👀 </b> \n \tThe profiles you fill out will be visible to other bot users who are also looking for a partner to start a family with . Please , only provide information that you are willing to share with others . \n\n 7. <b> Prohibited actions 🚨 </b> \n \tIt is prohibited : \n \t- Using the bot for commercial purposes . \n \t- Posting false information \n \t- Sending spam or advertising \n \t- Any form of aggression or harassment . ⛔ ️ \n\n 8. <b>Support 🆘 </b> \n \tIf you have any questions or problems , you can always contact support via the /help command. \n\n 9. <b> Getting started 🚀 </b> \n \tTo get started , " ✅ I accept" and fill out the form. After that, the bot will offer you suitable profiles for dating .',
        'confirm_terms_button': ' ✅ I accept ',
        'hello': '<b> 💌 Welcome!</b> \n\n We are glad that you are here! Our bot is created for those who are looking for a serious relationship and want to meet their soulmate . \n\n 1️ ⃣ Fill out your profile. \n 2️ ⃣ View profiles of other users . \n 3️ ⃣ Find someone who will inspire you!',
        'language': ' 🌍 Select the bot language ', 'back': ' 🔙 Back', 'profile_button': ' 👤 My profile ',
        'profile': '<b> 👤 Profile </b> \n\n <b>Username:</b> {username} \n <b> 💵 Your balance:</b> {balance} \n {tokens}<b> ✨ VIP status :</b> {vip} \n {super_vip}<b> 📋 Profile status :</b> {form_status} \n {boost}',
        'super_vip_widget': ' 🔱 <b>SUPER-VIP:</b> {super_vip} \n ',
        'form_boost_widget': ' 📈 <b> Profile boost </b> {form_boost} \n ',
        'tokens_widget': '<b> ⚡ ️ Tokens :</b> {tokens} \n ', 'vip_enable_widget': 'Active until {vip}',
        'vip_enable_women': 'Active', 'vip_disable_widget': 'Disabled', 'form_enable_widget': 'Active',
        'form_disable_widget': 'Disabled', 'disable_button': ' ❌ Disable profile ',
        'enable_button': ' ✅ Enable profile ',
        'my_form_button': ' 📋 My profile ', 'see_form': '<b>Your profile</b>', 'change_name_button': ' Change name ',
        'change_age_button': ' Change age ', 'change_male_button': ' Change gender ',
        'change_city_button': ' Change city ',
        'change_profession_button': ' Change profession ', 'change_education_button': ' Change education ',
        'change_income_button': ' Change income ', 'change_plans_button': ' Change text about yourself ',
        'change_religion_button': ' Change religion ',
        'change_second_wife_button': ' Change data about the possibility of a second wife ',
        'change_family_button': ' Change data about marital status ',
        'change_children_count_button': ' Change the presence of children ',
        'change_children_button': ' Change the field about children ',
        'change_leave_button': ' Change the field about moving ', 'change_photos_button': ' Change photos ',
        'change_male': ' To change your gender you will need to fill out your profile again \n\n <em> ❗ After you start filling out your profile again, your <b>VIP status </b> will be disabled </em>',
        'start_form_button': ' 🔄 Fill out your profile again ', 'my_balance_button': ' 💵 My balance ',
        'language_button': ' 🌎 Change language ', 'refs_button': ' 🎁 Earnings on referral',
        'ref': '<b> 🎉 Referral program </b> \n\n Invite friends and get money for their purchases! \n\n <em> 🔗 Your referral link :</em> <code>https://t.me/SR_znakomstva_bot?start={user_id}</code> \n\n 👥 Number of invited friends : {refs} \n\n <b> 💰 Referral program benefits :</b> \n\n You get 50% of the cost of all your referrals deposits . \n Earn without limits - the more friends , the higher your balance! \n <b> How does it work ?</b> \n 1️ ⃣ Copy the referral link . \n 2️ ⃣ Share it with your friends . \n 3️ ⃣ Every time your referrals make purchases , you automatically receive a reward to your balance . \n\n 🎯 Start inviting and earning now !',
        'share_button': ' 🌐 Invite friends ', 'ref_static_button': ' 📊 Statistics on your referrals',
        'ref_static': '<b> 📊 Statistics on your referral earnings </b> \n\n <b> My referrals :</b> {refs} \n <b> Total income from referrals :</b> {income} \n <b>Your balance:</b> {balance} \n <b> Funds withdrawn from balance :</b> {money}',
        'search_partner_button': ' 🔍 Search for a partner ',
        'search': '<b> 🔍 Menu for selecting profiles</b> \n\n Here you can select the criteria for searching for profiles or entrust the search for a partner to us ',
        'search_button': ' 🔎 Search for profiles ', 'filter_button': ' ⚙ ️ Search settings',
        'vip_filter_only_warning': ' ❗ This feature is only available to users with VIP',
        'filter': ' 🔍 Specify the parameters for selecting a profile \n Specified parameters : \n {params}',
        'filter_age_text': '<b> Age :</b> {min_age} to {max_age}', 'filter_city_text': '<b>City:</b> {text}',
        'filter_family_text': '<b> Marital status :</b> {text}',
        'filter_children_text': '<b> Attitude to having children :</b> {text}',
        'filter_religion_text': '<b> Religion :</b> {text}', 'filter_photo_button': 'Only with photo',
        'filter_age_button': ' 🕖 Age ', 'filter_city_button': ' 🏙 City', 'filter_family_button': ' 💍 Marital status ',
        'filter_children_button': ' 🍼 Attitude to having children ', 'filter_religion_button': ' 🙏 Religion ',
        'start_filter_button': ' 🔎 Find a partner ',
        'get_family': ' 💍 Specify the marital status of the partner you are looking for ',
        'get_children': ' 🍼 Specify the attitude of the sought partner to the proposal to have children ',
        'get_religion': ' 🙏 Specify the religion of the sought partner ', 'requests_button': ' 💬 My requests ',
        'requests': ' Here you can view the requests that you have sent , as well as requests sent to you .',
        'my_requests_button': ' My requests ',
        'no_my_requests': ' ❗ You have not made any communication requests yet , in the future when sending a request you will be able to view and manage them here ',
        'cancel_my_request_button': ' ❌ Cancel request ',
        'success_cancel_my_request': ' Your request has been successfully canceled ',
        'complain_request_button': ' 🚨 Complain ', 'alien_requests_button': ' Received requests ',
        'delete_form_warning': ' ❗ Unfortunately, the user profile has been blocked and deleted ',
        'no_alien_requests': ' ❗ You have not received any communication requests yet , in the future you will be able to view and accept communication requests here ',
        'confirm_alien_request_button': ' ✅ Accept request', 'decline_alien_request_button': ' ❌ Reject ',
        'success_decline_alien_request': ' The request was successfully rejected ',
        'success_my_request': '<b> Congratulations on your new acquaintance 🎊🎉 </b> \n\n Here is the user"s contact : @{username}',
        'success_alien_request': '{form} \n\n <b> Congratulations 🎊🎉 </b>. This person has accepted your request to chat \n\n Here is the user"s contact : @{username}',
        'balance_button': ' 💵 Balance and VIP status ',
        'balance': '<b> 💳Balance</b> \n\n <b> 💵 Your balance</b>: {balance} \n {tokens}<b> ✨ VIP status </b>: {vip} \n {super_vip}{boost}',
        'balance_menu_button': ' 🏦 Balance management ',
        'balance_menu': '<b> 💵 Your balance</b>: {balance} \n\n <em> You can view the entire history of deposits and debits from your balance in the transaction history </em>',
        'fill_button': ' ➕ Top up your balance ', 'derive_button': ' 🛒 Withdraw funds ',
        'balance_fill': ' Enter the amount you wish to top up ',
        'fill_error': ' ❗ The amount to top up must be a number ',
        'balance_derive': ' Enter the amount you would like to withdraw from your balance ',
        'derive_integer_error': ' ❗ The amount to withdraw must be a number ',
        'derive_balance_error': ' ❗ The amount to withdraw cannot be greater than your balance ',
        'success_derive_application': ' Your withdrawal request was successfully sent \n One of the administrators will contact you shortly ',
        'payment_button': ' 💰 Purchase tokens ',
        'choose_tokens': '<b> Select a rate for replenishing your balance </b>',
        'tokens_confirm': ' Do you confirm the purchase of {tokens} tokens in the amount of {price} rubles?',
        'confirm_tokens_button': ' 💲 Purchase ',
        'insufficient_funds_warning': ' ❗ ️ There are not enough funds on your balance to purchase tokens, to replenish your balance, go to the menu <b>" 💵 Balance and VIP status "</b> and select the balance management item , there you can replenish the bot balance ',
        'success_tokens_buy': ' Tokens have been successfully credited to your balance ',
        'choose_payment': ' 🏦 Select a convenient payment type ', 'card_pay_button': ' 💳 Payment by card',
        'crypto_pay_button': ' ⭐ ️ Payment by stars', 'payment_widget': 'Purchase by stars',
        'get_pay': ' Make a payment and then without leaving this menu <b>MANDATORY</b> wait for the bot to confirm your payment ',
        'url_button': ' 💻 Pay ', 'success_payment': ' ✅ Payment was successful',
        'referral_payment': ' Your referral has topped up their balance , you have received your percentage from the top-up 💰 ',
        'vip_button': ' 👑 VIP status ',
        'vip': '<b> ✨ Benefits of VIP status </b> \n\n <b> VIP status opens up more opportunities to find your soulmate :</b> \n\n 💌 Discount on communication requests \n The cost of communication requests is reduced by 50% - communicate more , spending less! \n\n 📈 Priority in recommendations \n Your profile will be shown higher in the list of recommendations , increasing your chances of success . \n\n <b> 🔍 Advanced profile search </b> \n Get access to more detailed search filters to find exactly those who match your criteria . \n\n <b> 💳 Subscription cost and conditions </b> \n\n ➡ ️ <b>1 day VIP</b> — 299 rubles . \n ➡ ️ <b>3 days VIP</b> — 499 rubles . \n ➡ ️ <b>7 days VIP</b> — 999 rubles . \n\n 🌟 Become a VIP and get closer to your dream of true love ! ',
        'on_vip_button': ' ✅ Purchase vip', 'choose_vip': ' Select the tariff you would like to connect ',
        'one_day_button': '1 day - 299 rubles', 'three_day_button': '3 days - 499 rubles',
        'one_week_button': '7 days - 999 rubles',
        'on_vip_error': ' 😔 Unfortunately, you do not have enough tokens on your balance ',
        'on_vip_success': ' ✅ VIP status has been successfully activated ',
        'vip_extension': ' ✅ VIP status has been successfully extended ',
        'not_enough_tokens': ' 😔 Unfortunately, your <b>VIP- status </b> has come to an end , but you can connect it again to continue actively searching for your soulmate ',
        'alert_about_vip_end': ' ‼ ️ <b> Attention , exactly 24 hours later your <b>VIP- status </b> will be deactivated </b>',
        'super_vip_button': ' 🔱 SUPER-VIP',
        'super_vip': ' ⚜ ️ When connecting <b>SUPER-VIP- status </b> you you will no longer need to send requests - you will be able to write to the profile owner directly .',
        '3_hours_super_vip_button': ' ⏩ 3 hours - 999 rubles', '7_hours_super_vip_button': ' ⏩ 7 hours - 2499 rubles',
        'day_super_vip_button': ' ⏩ 24 hours - 4999 rubles',
        'super_vip_on': ' ✅ SUPER-VIP status has been successfully activated ',
        'super_vip_off': ' 😔 Unfortunately, your <b>SUPER-VIP status </b> has expired , but you can reactivate it to continue actively searching for your soulmate ',
        'boost_button': ' 📈 Profile boost ',
        'boost': ' 📈 With a profile boost, your profile will be at the <b> very top of </b>, and more girls will see it .',
        '3_hours_boost_button': ' ⏩ 3 hours - 299 rubles', '7_hours_boost_button': ' ⏩ 7 hours - 499 rubles',
        'day_boost_button': ' ⏩ 24 hours - 999 rub',
        'boost_on': ' ✅ Profile boost has been successfully activated , for the next {hours} hour(s) your profile will be at the <b> top of the search</b>',
        'boost_off': '😔 Unfortunately, the profile boost service has ended , but you can still reactivate it to continue being at the top of the search',
        'history_button': ' 📋 Transaction history', 'history': '<b>Your transaction history document</b>',
        'info_button': ' 🛠 Rules and instructions',
        'women_info': '<b> 📖 Instructions for girls </b> \n\n Welcome to the dating bot ! Here you can find your ideal life partner . Using the bot is completely free for you , and you can meet without restrictions . Here`s how it works : \n\n <b> ❓ How to send a dating request ? \n </b>1. Find the profile of the man you like . \n 2. Click the <b>" Send Request "</b> button. \n 3. Your request will be sent and the man will receive a notification. \n\n <b> 💌 What happens after you send a request ?</b> \n - The man can accept your request. In this case, you can start chatting . \n - The man can decline your request. In this case, it`s okay - you can continue meeting other people . \n\n <b> 💡 Important to know :</b> \n - You can send <b> an unlimited number of </b> dating requests . No restrictions ! \n - You don`t need to pay tokens or make any payments - everything is completely free for girls . \n - You can accept or decline requests that men send you . It`s also free . \n\n <b> 💬 How to start a conversation ?</b> \n - If a man has accepted your request , you will automatically get access to a chat with him . \n - If you have accepted a request from a man , you will also be able to start a conversation . \n\n <b> 💡 Tips :</b> \n - Read profiles carefully to send requests to those you are really interested in . \n - Don`t be afraid to take the initiative - send requests first! \n - Use the opportunity to meet different people to find the one who is right for you . \n\n If you still have questions , write to support through the bot menu. Good luck in finding your happiness! ❤ ️ ',
        'men_info': '<b> 📖 Instructions for using the bot </b> \n\n Welcome to the dating bot ! Here you can find your soulmate and create a strong family . \n\n <b> 🎁 Bonus for new users !</b> \n When you register, you get <b>50 free </b> tokens to start dating without investment . Use them wisely! \n\n <b> 💎 What are tokens ?</b> \n Tokens are the bot`s internal currency that allows you to interact with other users . You can purchase tokens by clicking the " Balance " button and use them to send and accept dating requests . \n\n <b> ❓ How to send a dating request ?</b> \n 1. Find a profile you like . \n 2. Click the <b>" Send request "</b> button. \n 3. If you have enough tokens , the request will be sent and if it is accepted, you will receive a notification . \n\n <b> 💸 How many tokens are debited ?</b> \n - If you send a dating request and a girl <b> accepts it </b>, <b>10 tokens</b> will be debited from your account . \n - If the girl <b> rejects </b> your request , <b> tokens are not written off </b>. \n - If you receive a dating request and you accept it , 10 tokens will also be written off from your account . \n\n <b> ❗ ️ Important!</b> \n - Tokens are written off only if the request from the girl is accepted; if she does not accept the request, nothing will be written off from you . \n - Also, if the girl sent a request and you do not have enough tokens , you will not be able to accept the request . \n - You can top up your token balance at any time through the bot menu . \n\n <b> 🛒 How to buy tokens ?</b> \n\n 1. Go to the "<b> Balance and VIP</b>" section. \n 2. Select the token package that suits you . \n 3. Pay for the selected package in a convenient way . \n\n <b> 💡 Tips :</b> \n - Carefully read the profiles to send requests to those you are really interested in . \n - Top up your token balance in advance so as not to interrupt the dating process . \n - Use your <b>50 free </b> tokens for first acquaintances to evaluate the bot`s capabilities . \n\n If you still have questions , write to support through the bot menu. Good luck in finding your soulmate! ❤ ️ ',
        'help_button': ' 🆘 Help and support ',
        'help': '<b> We are always ready to help if you have any questions or difficulties! 💬 </b> \n\n <b> ❓ Frequently asked questions (FAQ):</b> \n 1️ ⃣ How to top up your token balance ? \n <em> Go to the "Balance and VIP status" section in the bot menu and choose a convenient replenishment method .</em> \n\n 2️ ⃣ What does VIP status give ? \n - The cost of communication requests is reduced by 50%. \n - Your profile rises to the top of the search , which increases the chances of meeting someone . \n\n 3️ ⃣ How do I change my data ? \n <em> Open your profile through the "My profile" menu and edit the necessary fields .</em> \n\n <b> If the problem is not solved :</b> \n Write to our administrator : @SR_support_me. \n Describe the problem in as much detail as possible so that we can quickly help . \n ✨ We are available 24/7 and will do everything to make your experience enjoyable ! ',
        'contact_button': ' 📞 Contact support ', 'registration_button': ' 📝 Register ',
        'add_name': ' 💬 Enter your name ',
        'add_name_error': ' ❗ ️ Cannot be more than 50 characters , please try again ',
        'add_age': ' 🕖 Enter your age (from 18 to 99) ',
        'add_age_range': ' 🕖 Enter your age (from 18 to 99) in the format: 20-30 or 38-47 ',
        'add_age_range_error': ' ❗Your age can only be in the range from 18 to 99 and must be a number written in the format : 20-30 or 38-47 ',
        'add_age_error': ' ❗ ️ Your age can only be in the range from 18 to 99 and must be a number ',
        'add_male': ' 🚹🚺 Please indicate your gender', 'men_button': 'Male', 'women_button': ' Female ',
        'add_city': ' 🏙 Please enter the name of your city or town or send the geolocation of the place where you are ',
        'location_request_button': '📍Send your geolocation',
        'add_city_name_error': ' ❗ ️ Unfortunately, the city | village with this name was not found, please try again',
        'add_city_geo_error': ' ❗ ️ Unfortunately, no settlements were found for this geo , please try again',
        'add_profession': ' 💼 Specify your profession or occupation .',
        'add_profession_error': ' ❗ ️ The name of your profession must contain no more than 100 characters ',
        'add_education': ' 🎓 Your level of education ', 'add_education_leaning_button': ' Still studying ',
        'add_education_eleven_button': '11 grades ', 'add_education_average_button': ' Secondary vocational ',
        'add_education_higher_button': ' Higher ', 'add_income': ' 💰 Specify your income level',
        'add_income_no_button': 'No income', 'add_income_low_button': 'Low', 'add_income_average_button': 'Average',
        'add_income_high_button': ' High ', 'add_plans': ' 🌟 Tell us a little about yourself (up to 1000 characters )',
        'add_plans_error': ' ❗ ️ The text must contain no more than 1000 characters ',
        'add_religion': ' 🙏 What your faith is ', 'add_religion_christian_button': ' Christianity ',
        'add_religion_islam_button': ' Islam ', 'add_religion_another_button': ' Other ',
        'add_second_wife': ' 👨 \u200d 👧 \u200d 👧 Are you ready to marry a second wife .',
        'add_second_wife_yes_button': ' Yes ', 'add_second_wife_no_button': 'No',
        'add_family': ' 💍 Please indicate your marital status',
        'family_button': ' Married . Looking for a second wife ',
        'no_family_button_women': ' Never married ', 'no_family_button_men': ' Never married ',
        'divorce_family_button_women': 'Divorced', 'divorce_family_button_men': 'Divorced',
        'widow_family_button_men': 'Widower', 'widow_family_button_women': 'Widow',
        'add_children_count': ' 👶 Do you have children , if so, write their number ',
        'add_children_count_no_button': 'No',
        'add_children_count_error': ' ❗ ️ The number of children must be a number ',
        'add_children': ' 🍼 Do you want to have children ? ', 'add_children_yes_button': ' Yes ',
        'add_children_no_button': 'No', 'add_children_maybe_button': ' Maybe ',
        'add_children_not_matter_button': ' Doesn`t matter ',
        'add_leave': ' 🚗 Are you ready to move to another city or country ? ', 'add_leave_yes_button': ' Yes ',
        'add_leave_no_button': 'No',
        'add_photo_1': ' 🌄 Add at least one photo to your profile to attract more attention . Profiles with photos are shown higher in the search than those without a photo . This will increase your chances of being noticed! \n\n <b> Requirements : your face must be clearly visible .</b>',
        'add_photo_2': ' 🌄 Upload a second photo \n\n <b> Requirements : your face must be clearly visible .</b>',
        'add_photo_3': ' 🌄 Upload a third photo \n\n <b> Requirements : your face must be clearly visible .</b>',
        'add_photo_skip': ' Skip ',
        'check_photos': '<b> Your photos have been sent for moderation , please wait.</b> \n <em> Once moderation approves the photos, they will be automatically added to your profile </em>',
        'women_vip': 'You have <b>VIP status </b>',
        'add_form_notification': ' 🎊 <b>Your profile has been successfully created!</b> You have received 30 tokens as a gift . Please use them wisely . \n\n To view or edit your profile , click the button "<b> 👤 My profile </b>"',
        'women_vip_proposal': '<b> You have the opportunity to get unlimited VIP status </b> \n\n <b>VIP status </b> opens up these opportunities : \n\n 📈 Priority in recommendations \n Your profile will be shown higher in the list of recommendations , increasing your chances of success . \n\n <b> 🔍 Advanced profile search </b> \n Get access to more detailed search filters to find exactly those who match your criteria .',
        'women_verification_button': ' 🎁 Get VIP ',
        'women_verification_note': ' In order to get <b>VIP- status </b> send a video -circle and say <em>"Hello, I ( name ) want to start a family ."</em> \n\n <em> ⚠ ️ This is necessary so that we can make sure that you are a woman </em>',
        'wrong_verification_message': ' ❗ The message must be in the video -circle format, please try again<',
        'success_get_video_note': ' ✅ The application for receiving <b>VIP- status </b> has been sent , after approval of the application you will receive <b>VIP- status </b>',
        'success_vip_verification': ' ✅ Your application for receiving <b>VIP- status </b> was successfully approved ',
        'form_error': ' ❗ Unfortunately, something went wrong , we could not find any profiles that suit you , please <b>try again</b> or <b> try setting up filtering </b> profiles ',
        'no_location_warning': '❗Before you start viewing profiles, please add your geolocation in the "👤My Profile" menu -> "📋My Profile" -> "Change City"',
        'no_filter_forms': ' ❗ There are no more profiles matching your settings ',
        'basic_search_button': ' 🔎 Regular search ', 'filter_search_button': ' ⚙ ️ Set up search ',
        'form': ' 💬 Name {name}, {male}, {age} {age_text}, city {city} ( 📍 {distance} km from you) \n\n <b> 💼 Work:</b> {profession}. \n <b> 🎓 Education :</b> {education}. \n <b> 💰 Income:</b> {income}. \n\n <b> 🌟 About me:</b> \n {description} \n\n <b> 🙏 My religion :</b>{religion}. \n <b> 💍 Marital status :</b> {family}. \n {second_wife}<b> 👶 Children</b>: {children_count}. \n <b> 🍼 Desire to have children:</b> {children}. \n\n <b> 🚗 Willingness to move :</b> \n {leave} \n\n <b>VIP user :</b> {vip}',
        'second_wife_form_widget': ' 👨 \u200d 👧 \u200d 👧 Ready to marry second wife : {second_wife} \n ',
        'next_form_button': ' Next ', 'complain_form_button': ' Leave a complaint ',
        'get_complain': ' Please describe the essence of the complaint so that later one of the admins can understand the essence of the problem in more detail ',
        'success_complain_add': ' The complaint has been sent! Thank you for helping to strengthen our community ❤ ️ ',
        'contact_form_button': ' Send request ',
        'add_request_error': ' ❗ ️ You have already sent a request for communication on this profile ',
        'add_request_success': ' You sent a request to the owner of the profile . Now she will be able to see your request and decide : to accept it or reject it . ',
        'no_tokens_warning': ' Unfortunately, you do not have enough tokens to accept the application , to top up your balance, please go to the "<b> Balance and VIP</b>" section. ',
        'success_men_send': ' ❗ As soon as the man confirms the request for communication, his contact information will be immediately sent to you ',
        'success_apply_request': '{form} \n\n ❗ ️ The girl accepted your request for communication , to get her contact, click on the button below . You will be charged 10 tokens for receiving a contact.',
        'get_contact_button': ' 🎁 Get contact ',
        'add_request_message': ' ❗ ️ <b> You received a request for communication </b>, to view it, go to the " 💬 My requests " section ',
        'form_info_button': 'Instructions', 'close_info_button': ' ❌ Close instructions ',
        'warning_message': ' 🚨🚨 <b> You received a warning </b>: \n\n ',
        'block_message': '<b> Unfortunately, you were blocked due to violation of the bot rules </b> \n You will no longer be able to use the bot`s functions ',
        'photos_warning_message': ' 🚨🚨 <b> Unfortunately, your photos do not meet the requirements for a profile photo </b> \n\n In order for your profile to display photos, please try adding new photos in the profile section ',
        'again_create_warning': ' 🚨🚨 <b> Your profile was reset </b>, here is a message from the admin: \n ',
        'no_form_warning': '<b> To fully use the bot, please create your profile </b>',
        'check_sub': ' ❗ To continue using the bot, please subscribe to these channels ',
        'check_sub_button': ' Check subscription ', 'check_sub_warning': ' 🚨 You have not subscribed to all channels ',
        'check_sub_success': 'The check was successful, you can continue using the bot ', 'rub': ' rubles ',
        'info': ' 💡 Here you can read the rules of the bot , as well as figure out how to use it ',
        'info_dialog_button': ' ℹ ️ Instructions', 'rules_button': ' ❗ ️ Rules',
        'rules': '<b> Rules and conditions for using the dating bot to create 🌟 </b> \n\n 1. <b>Bot goal 💍 </b> \n \tThis bot was created for people who are looking for a serious relationship and strive to create a strong family . We welcome sincerity , respect and readiness for long-term commitments . \n\n 2. <b> Age restriction 🚫 </b> \n \tOnly persons over 18 years of age are allowed to use the bot. By registering in the bot , you confirm that you have reached the age of majority . \n\n 3. <b>Registration and questionnaire 📝 </b> \n \tTo start using the bot, you must fill out a questionnaire , indicating reliable information about yourself . The more honestly and in detail you tell about yourself , the higher the chance of finding a suitable person . \n\n 4. <b> Respect for other users </b> \n \tWe do not tolerate insults , rudeness or disrespectful behavior . Each user deserves an attentive and friendly attitude . \n\n 5. <b> Sincerity in communication 💬 </b> \n \tWe encourage you to be honest in your intentions . If you are looking for a serious relationship , please indicate this in your profile and communication . \n\n 6. <b> Profile visibility 👀 </b> \n \tThe profiles you fill out will be visible to other bot users who are also looking for a partner to start a family with . Please only provide information that you are willing to share with others . \n\n 7. <b> Prohibited actions 🚨 </b> \n \tIt is prohibited : \n \t- Using the bot for commercial purposes . \n \t- Posting false information \n \t- Sending spam or advertising \n \t- Any form of aggression or harassment . ⛔ ️ \n\n 8. <b>Support 🆘 </b> \n \tIf you have any questions or problems , you can always contact support via the /help.',
        'notification_message': '<b>{name} command, today {count} new profiles from a city near you appeared !</b> \n Who knows , maybe your person is among them ? 😊 It will only take a couple of minutes to view them . \n\n <b> New people appear every day . Don`t miss your chance to find your soulmate 😉 </b>',
        'notification_button': ' 🔴 Referral ',
        'no_username_warning': ' 🚨 <b> Before using the bot , please add a username to your account so that your soulmate can contact you </b>'
    }
}
